### ISSUE TITLE
Wrong textures on Raspberry Pi

### ISSUE THREAD

**Issue by jmcerrejon** [vsonnier/vkQuake-vso#6]
**Describe the bug**
Wrong textures on Raspberry Pi.

**To Reproduce**
Compile the sorurce code, copy the id1/ game data directory and run.

**Expected behavior**
Right textures.

**Screenshots**
![Screenshot 2024-03-07 at 13 55 09](https://github.com/vsonnier/vkQuake-vso/assets/1942431/b10ee2a6-40e4-496a-96bd-4deec0e0c36a)

**Desktop (please complete the following information):**
 - OS: Raspberry Pi OS 64-bit Booksworm
 - Mesa driver 24.0.0

![Screenshot 2024-03-07 at 14 11 54](https://github.com/vsonnier/vkQuake-vso/assets/1942431/5c51ed53-fed6-4ca8-9c4c-b2e25dcd8a29)

**Mod**
No mods

**Comment by vsonnier** [comment]
Hello,

You'd better direct this bug to the Mesa developpers, since it works on other pltaforms this is obviously a driver bug. 

For one thingn the Vulkan rendering code has been extensivly tested in the original vkQuake, it has not changed one bit since then,  aannnd I wouldn't be able to change it anyway, not to mention test on your particular platform.

And the original author thinks the same : https://github.com/Novum/vkQuake/issues/616
