### ISSUE TITLE
error when trying to save/load a savegame 

### ISSUE THREAD

**Issue by j4reporting** [vsonnier/vkQuake-vso#7]
This happens sometimes, although very rarely, during a longer session ie  playing a big map and several save/load cycles. Not really sure how to replicate this and I have to admit this time I realized too late, what was going on and did not investigate more.  Quit and Re-start cycle fixes this.

Map was ad_magna   and the quick save game was NOT overwritten.  The previous savegame was still intact.  Was able to load the old savegame after restart.  Unfortunately I haven't  try to load other savegames, but I would  guess  it would have failed as well. 

any idea what the reason  might be for this?

![vkquake-vso_error](https://github.com/vsonnier/vkQuake-vso/assets/45177907/ccaa772e-a8f5-49f1-8a26-9810cfa4b790)

**Comment by Macil** [comment]
I wonder if the process could be running out of open file handles and unable to open any more. There could be a file handle leak in loading the map data.

**Comment by vsonnier** [comment]
Hello @j4reporting, I assume you have something like that in either your `autoexec.cfg` or `vkQuake.cfg` to enable quicksaving:

```c
bind "F5" "echo Quicksaving...; wait; save quick"
bind "F6" "echo Quickloading...; wait; load quick"
```

also what are your values for the following Cvars:

```c
cvar_t autoload = {"autoload", "1", CVAR_ARCHIVE};
cvar_t autofastload = {"autofastload", "0", CVAR_ARCHIVE};
```
I'll try to follow the corresponding code paths trying to see if we lost file handles along the way.

**Comment by vsonnier** [comment]
>  It seems I can recreate this simply by playing ad_magna.

>  Interesting fact, the load and save screens show no available savegames. Every slot is empty.

> quicksave/load are default but re-assigned to F6 / F9

> I also use F2/F3 to save/load from the default savegame slots s[0-19].sav .

> in case this is important... this is the content of C:\games\vkquake\

Thanks @j4reporting, however I need to be the closest to you configutation. Thankfully there is a simpler way than detailing everything : attach a zip of your `ad` and `id1` dir without  the content of course, that should contain have someting like:

```c
id1/autoexec.cfg
id1/vkQuake.cfg
ad/vkQuake.cfg
ad/save*.sav
ad/quake.rc
```
 and describe your way to launch and run `ad_magna` and such.

**Comment by vsonnier** [comment]
BTW are you the 'j4r' that helped me about GCC 14 on https://www.slipseer.com/ site ? I goes by 'vso' there, and the icon is the same as here.

**Comment by vsonnier** [comment]
Thanks @j4reporting, I've installed your setup, and _of course_  , did not manage to reproduce the problem for the (relatively short) time I toyed with it.

Still, there is something I don't like the way the saves are loaded in the current Quakespasm and changed the method in the tentative fix you can see above.

I've never played AD beyond the test maps  before so now I'm going to play `ad_magna` and save a lot, for _science_. 

If you have the time, please try this fix and tell me if the problem is gone or not for you.

**Comment by vsonnier** [comment]
Great catch @j4reporting ! Ironwail has the same problem because this is where I cherry-picked the code in the first place :)

Indeed with that fix, I no longer see an Handle count increase in Process Explorer, while it was 20 more or so at each load like you noticed.

I've pushed that fix on the vkQuake `master`. My tentative (non)-fix will stay on vkQuake-vso for now.

Since you are a fan of quicksaves, consider using `autofastload 1` to have near-instantaneous loadings. 

Of course, with such a setting the handle leak would have been non-existent since no resources are reloaded if the current map is the same as the save. I good thing you didn't use that before !

**Comment by j4reporting** [comment]
I think under Unix/Linux  I could have found it  more easily with trace and lsof. I kind of tricked myself  using process explorer on Windows. I always double-clicked on the process to open the process information window. But it shows only the number of handles and no specific handle details.
Instead I needed to activate  the lower pane in the main window to display the files referenced by the handles...  not very intuitive 

I kind of always suspected that ironwail might have the same issue. I rember someone already mentioned something similar in an ironwail issue. 
Of course, once you find a quick and easy way to reproduce...
